### ISSUE TITLE
Issue with EmojiAttributes 1.3.26 (iOS 11.3)

### ISSUE THREAD

**Issue by LileAuTresor** [PoomSmart/EmojiAttributes#11]
Hi,
Emoji are no longer displayed correctly since the update of EmojiAttributes 1.3.26 (ios 11.3). It's the same with Anemone and EmojiFontManager.
I tried to downgrade to 1.3.25 but it doesn't change anything while everything was working before.
Can you look ?
![70DAD26F-CCB9-4214-8253-0D8F9E89E578](https://user-images.githubusercontent.com/42318092/82157986-2ceca500-9885-11ea-9edb-1b8f1c3ea751.jpeg)

**Comment by LileAuTresor** [comment]
It's strange, I deleted everything, cleaned with icleaner and reinstalled all with version 1.3.25 and everything works...

**Comment by PoomSmart** [comment]
I tested on my local iOS 11.3 environment but did not see this issue. Is this more like of issues with emoji font?

**Comment by LileAuTresor** [comment]
I don't know, I downloaded the font on https://vxbakerxv.github.io/repo
If I have to test something tell me, otherwise I stay in version 1.3.25 for the moment.

**Comment by PoomSmart** [comment]
There is 1.3.27 in case you want to try.

**Comment by LileAuTresor** [comment]
1.3.27 works great with 13.2 font, thank you ! You can close the issue.
