### ISSUE TITLE
iOS crashes when the numeric keyboard attempts to load (1.4.1~b5 - iOS 10.2.1)

### ISSUE THREAD

**Issue by MrDemocracy** [PoomSmart/EmojiAttributes#12]
After updating EmojiAttributes today my iPhone has started to freeze when the numeric keyboard attempts to load, and after a while the device reboots.

**Comment by PoomSmart** [comment]
Which iPhone is it? @MrDemocracy

**Comment by MrDemocracy** [comment]
iPhone 6S

**Comment by PoomSmart** [comment]
@MrDemocracy Does this happen everywhere? SpringBoard? App Store apps? System apps?

**Comment by MrDemocracy** [comment]
I've only tried the with settings app and an app from cydia. With the app from cydia, the device didn't reboot, it jsut froze for a while and then the app crashed. It was in a in-app browser window.

**Comment by PoomSmart** [comment]
@MrDemocracy Can you provide any crash logs?

**Comment by MrDemocracy** [comment]
Where do I find that? I have crashreporter installed, but it didn't detect any crashes.

**Comment by PoomSmart** [comment]
How about b8?

**Comment by MrDemocracy** [comment]
It's no longer freezing when the numeric keyboard is displayed on b8.
