### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by dodieboy** [PoomSmart/EmojiAttributes#18]
My application (Coinhako) crash after updating to 1.5.0 b8 (crash on b10 and b11 too)

**Comment by dodieboy** [comment]
Here is the crash log

Date: 2/21/22, 11:51 AM
Process: Coinhako
Bundle id: com.coinhako.app
Device: iPhone 12 Pro, iOS 14.1
Bundle version: 4.0.0

Exception type: EXC_BAD_ACCESS (SIGSEGV)
Exception subtype: KERN_INVALID_ADDRESS: 0x0
Exception codes: 0x0000000000000001, 0x0000000000000000
Culprit: EmojiPortPE.dylib
VM Protection: 0x0 is not in any region.

Triggered by thread: 0
Thread name: Dispatch queue: com.apple.main-thread
Call stack:
0   EmojiAttributes.dylib         	0x000000010a1d12b4 0x10a1cc000 + 21172      	// EmojiProps_load(UErrorCode&)
1   EmojiAttributes.dylib         	0x000000010a1d12a4 0x10a1cc000 + 21156      	// EmojiProps_load(UErrorCode&)
2   EmojiAttributes.dylib         	0x000000010a1d0fd8 0x10a1cc000 + 20440      	// _logosLocalCtor_dffe3383(int, char**, char**)
3   dyld                          	0x0000000105a8e624 0x105a74000 + 108068     	// ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
4   dyld                          	0x0000000105a8e8ac 0x105a74000 + 108716     	// ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
5   dyld                          	0x0000000105a88a94 0x105a74000 + 84628      	// ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
6   dyld                          	0x0000000105a869f0 0x105a74000 + 76272      	// ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
7   dyld                          	0x0000000105a86abc 0x105a74000 + 76476      	// ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
8   dyld                          	0x0000000105a7a4b8 0x105a74000 + 25784      	// dyld::runInitializers(ImageLoader*)
9   dyld                          	0x0000000105a82220 0x105a74000 + 57888      	// dlopen_internal
10  libdyld.dylib                 	0x00000001a693439c 0x1a692f000 + 21404      	// dlopen_internal(char const*, int, void*)
11  EmojiPortPE.dylib             	0x000000010a1c3d9c 0x10a1bc000 + 32156      	// func_7b84
12  dyld                          	0x0000000105a8e4a8 0x105a74000 + 107688     	// ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
13  dyld                          	0x0000000105a8e8ac 0x105a74000 + 108716     	// ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
14  dyld                          	0x0000000105a88a94 0x105a74000 + 84628      	// ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
15  dyld                          	0x0000000105a869f0 0x105a74000 + 76272      	// ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
16  dyld                          	0x0000000105a86abc 0x105a74000 + 76476      	// ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
17  dyld                          	0x0000000105a7a4b8 0x105a74000 + 25784      	// dyld::runInitializers(ImageLoader*)
18  dyld                          	0x0000000105a82220 0x105a74000 + 57888      	// dlopen_internal
19  libdyld.dylib                 	0x00000001a693439c 0x1a692f000 + 21404      	// dlopen_internal(char const*, int, void*)
20  substitute-loader.dylib       	0x00000001079075e0 0x107874000 + 603616     
21  substitute-loader.dylib       	0x0000000107ac6240 0x107874000 + 2433600    
22  substitute-loader.dylib       	0x0000000107ac6264 0x107874000 + 2433636    
23  substitute-loader.dylib       	0x0000000107ac6288 0x107874000 + 2433672    
24  substitute-loader.dylib       	0x0000000107a94aa8 0x107874000 + 2230952    
25  substitute-loader.dylib       	0x00000001079e9c00 0x107874000 + 1530880    
26  substitute-loader.dylib       	0x00000001079e8a48 0x107874000 + 1526344    
27  substitute-loader.dylib       	0x0000000107a212ec 0x107874000 + 1757932    
28  substitute-loader.dylib       	0x00000001079ed5b4 0x107874000 + 1545652    
29  dyld                          	0x0000000105a8e4a8 0x105a74000 + 107688     	// ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
30  dyld                          	0x0000000105a8e8ac 0x105a74000 + 108716     	// ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
31  dyld                          	0x0000000105a88a94 0x105a74000 + 84628      	// ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
32  dyld                          	0x0000000105a869f0 0x105a74000 + 76272      	// ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
33  dyld                          	0x0000000105a86abc 0x105a74000 + 76476      	// ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
34  dyld                          	0x0000000105a7a4b8 0x105a74000 + 25784      	// dyld::runInitializers(ImageLoader*)
35  dyld                          	0x0000000105a82220 0x105a74000 + 57888      	// dlopen_internal
36  libdyld.dylib                 	0x00000001a693439c 0x1a692f000 + 21404      	// dlopen_internal(char const*, int, void*)
37  substitute-inserter.dylib     	0x0000000105c4d23c 0x105b64000 + 954940     	// func_e8f2c
38  substitute-inserter.dylib     	0x0000000105f860a0 0x105b64000 + 4333728    	// func_422090
39  substitute-inserter.dylib     	0x0000000105f41340 0x105b64000 + 4051776    	// func_3d1760
40  dyld                          	0x0000000105a8e4a8 0x105a74000 + 107688     	// ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
41  dyld                          	0x0000000105a8e8ac 0x105a74000 + 108716     	// ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
42  dyld                          	0x0000000105a88a94 0x105a74000 + 84628      	// ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
43  dyld                          	0x0000000105a869f0 0x105a74000 + 76272      	// ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
44  dyld                          	0x0000000105a86abc 0x105a74000 + 76476      	// ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
45  dyld                          	0x0000000105a767a4 0x105a74000 + 10148      	// dyld::initializeMainExecutable()
46  dyld                          	0x0000000105a7bd58 0x105a74000 + 32088      	// dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*)
47  dyld                          	0x0000000105a75258 0x105a74000 + 4696       	// dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*)
48  dyld                          	0x0000000105a75038 0x105a74000 + 4152       	// _dyld_start

Register values:
PC: 0x0                 LR: 0x0                 CPSR: 0x0
x0: 0x0                 x1: 0x0                 x2: 0x0
x3: 0x0                 x4: 0x0                 x5: 0x0
x6: 0x0                 x7: 0x0                 x8: 0x0
x9: 0x0                 x10: 0x0                x11: 0x0
x12: 0x0                x13: 0x0                x14: 0x0
x15: 0x0                x16: 0x0                x17: 0x0
x18: 0x0                x19: 0x0                x20: 0x0
x21: 0x0                x22: 0x0                x23: 0x0
x24: 0x0                x25: 0x0                x26: 0x0
x27: 0x0                x28: 0x0

**Comment by PoomSmart** [comment]
Most likely your jailbreak detection bypass tweak is blocking access to a file that EmojiAttributes needs to access. I mitigated this by adding a warning alert to those kind of apps you have enabled bypass in b12.
