### ISSUE TITLE
Latest update cannot be installed on un0ver jb.

### ISSUE THREAD

**Issue by sahinkaa** [PoomSmart/EmojiAttributes#22]

**Comment by LilyMods** [comment]
![Uploading 720C6AB6-64F4-4E59-B4C7-AD138B31AFFB.png…]()

**Comment by LilyMods** [comment]
`An unknown error occurred.
APT was unable to find this package.
Please try refreshing your sources
W: Target Packages (main/binary-
iphoneos-arm/Packages) is configured
multiple times in /etc/apt/sources.list.d/
cydia.list:1 and /etc/apt/sources.list.d/
sileo.sources:3
W: Target Packages (main/binary-all/
Packages) is configured multiple times
in /etc/apt/sources.list.d/cydia.list:1
and /etc/apt/sources.list.d/
sileo.sources:3
W: Target Translations (main/i18n/
Translation-en) is configured multiple
times in /etc/apt/sources.list.d/
cydia.list:1 and /etc/apt/sources.list.d/
sileo.sources:3
W: Target Packages (Packages) is
configured multiple times in /etc/apt/
sources.list.d/cydia.list:3 and /etc/apt/
sources.list.d/sileo.sources:8
W: Target Translations (en) is
configured multiple times in /etc/apt/
sources.list.d/cydia.list:3 and /etc/apt/
sources.list.d/sileo.sources:8
W: Target Packages (Packages) is
configured multiple times in /etc/apt/
sources.list.d/cydia.list:4 and /etc/apt/
sources.list.d/sileo.sources:2
W: Target Translations (en) is
configured multiple times in /etc/apt/
sources.list.d/cydia.list:4 and /etc/apt/
sources.list.d/sileo.sources:2
W: Target Packages (Packages) is
configured multiple times in /etc/apt/
sources.list.d/cydia.list:7 and /etc/apt/
sources.list.d/sileo.sources:9
W: Target Translations (en) is
configured multiple times in /etc/apt/
sources.list.d/cydia.list:7 and /etc/apt/
sources.list.d/sileo.sources:9
E: Version '1.7.0~b3' for
'com.ps.emojiattributes' was not found `

**Comment by PoomSmart** [comment]
https://twitter.com/poomsmart/status/1640359662007746560?s=46&t=s24X5WUxto9pOL7U2Nos-A

**Comment by sahinkaa** [comment]
So, no solution for Zebra then. Only Sileo?

**Comment by PoomSmart** [comment]
Then your problem is Zebra.
