### ISSUE TITLE
EmojiAttributes & EmojiLibrary new update cause safemode on iOS 8.4 and some emoji only have one skintone

### ISSUE THREAD

**Issue by mkizzle2906** [PoomSmart/EmojiAttributes#4]
I update both of them on my 6Plus 8.4 and replace a new font file then they put my device into safemode. I tried to replace old font file & downgrade but still stuck in safemode. Only EmojiAttributes 1.3.13 & EmojiLibrary 1.0.12 work. Before updating to the lastest everything work fine. Can you check it ??? And after updating EmojiDarkStyle causes this on my iOS 8.4 devices
![img_3965](https://user-images.githubusercontent.com/32402155/46807418-0eaef100-cd94-11e8-8b1d-5c985c646abe.PNG)

Another problem is this emoji dont have skin selection. The lastest update of EmojiPort 10 - 11.4 fixed the people skin tone problems, 
but this emoji still only have 1 skin. (both iOS 9, 10 & 11)
![img_1407](https://user-images.githubusercontent.com/32402155/46806451-d0183700-cd91-11e8-9632-2f835359855f.PNG)

This emoji only on iOS 10 has one skin too
![img_3421](https://user-images.githubusercontent.com/32402155/46806704-749a7900-cd92-11e8-840c-959dd25f7552.PNG)

**Comment by SpicaT** [comment]
Hey.

I think the lack of skin support for the handshake emoji is intended in iOS. PoomSmart would probably just do whatever Apple do.

http://www.reddit.com/r/iphone/comments/940lmn/handshake_emoji_doesnt_have_color_options/

**Comment by mkizzle2906** [comment]
oh I didn't realize it, thought it was font bug, thanks
