### ISSUE TITLE
iOS 12.1 emoji not appear on iOS 9.0.2

### ISSUE THREAD

**Issue by r9hacks** [PoomSmart/EmojiAttributes#5]
I installed the iOS 12.1 emoji on my iPhone 6 iOS 9.0.2 using BytaFont 3. The emoji appear inside search bar, note and almost everywhere. But not on my WhatsApp or Clash Royale game. Any idea on how to fix this??

**Comment by PoomSmart** [comment]
Some apps block tweaks. Not a scope.
