### ISSUE TITLE
Incompatibility with NextUp 2

### ISSUE THREAD

**Issue by Nosskirneh** [PoomSmart/EmojiAttributes#8]
Hi @PoomSmart!

I'm the developer of [NextUp](https://henrikssonbrothers.com/cydia/repo/depictions/?p=se.nosskirneh.nextup2). At two reports of EmojiPort not working with NextUp have been sent my way. One of them specifically mentions EmojiAttributes while the other said "and its dependencies", so that's why I'm opening this issue here as opposed to at the EmojiPort repo.

[Issue 1](https://github.com/Nosskirneh/NextUp-Public/issues/18#issuecomment-491495877)
[Issue 2](https://github.com/Nosskirneh/NextUp-Public/issues/24)

My two iOS 12 devices are running 12.1.x and I thus cannot test this myself. I tried the iOS 11 version of EmojiPort on my iOS 11.1.2 device but I had no issues with NextUp for iOS 11. I would really appreciate you helping me out. I could let you in on the source code of my tweak if that would be necessary.

NextUp can be found on [this repo](https://henrikssonbrothers.com/cydia/repo/). There is a 10 day trial included, but I'd be more than happy to generate a full license for you (please send me your UDID in that case).

I know you just started a full time job (congrats by the way!), so please know that there is no rush in this. I'm just happy for any help in solving this as I am unable to solve it myself.

Take care,
Andreas

**Comment by PoomSmart** [comment]
Dear @Nosskirneh,

Thank you, the full time job is nice by the way.

I only own iOS 12.1.x devices, and the fact is that, EmojiPort has been reported promptly that it will not work on iOS 12.0.x devices. I am unable to figure out the culprit as it is more like an issue with tweak injection or the jailbreak itself.

It would be great to examine the source code of NextUp to see if there were any interferences with EmojiPort both directly and indirectly.

I would like to discuss more with you privately. Which channel do you prefer? Twitter? Something else?

**Comment by Nosskirneh** [comment]
Thank you for the answer! Private chat sounds great. Twitter works perfectly fine for me. It seems like your DMs are closed so feel free to message me:
https://twitter.com/aNosskirneh

**Comment by PoomSmart** [comment]
EmojiAttributes has been recompiled to work better on iOS 12.0, closing the issue
