### ISSUE TITLE
Issue with emoji size

### ISSUE THREAD

**Issue by LastPust** [PoomSmart/EmojiAttributes#9]
By default if you send a single emoji. It looks bigger. But new added emojis are always in small size.

Device is iphone 7
İos 12.4
Unc0ver latest
Your tweaks are at latest versions.

+ ı cant use memoji

**Comment by PoomSmart** [comment]
Which applications did you try on?

**Comment by LastPust** [comment]
Whatsapp (latest version)

**Comment by PoomSmart** [comment]
I assume this is WhatsApp issue not fully supporting iOS 13.2 emojis. Unless this doesn’t happen on a real iOS 13.2 b2 device, you should wait for app update. This has nothing to do with EmojiPort.

**Comment by LastPust** [comment]
I dont think its about whatsapp. When ever ios gets an update and adds new emojis there were no problems with any app. Ios 13 is out and whatsapp got its update for it.. just saying fix or not idc

**Comment by PoomSmart** [comment]
iPhone 11 iOS 13.2b2
The issue will be marked as invalid.

![Image](https://i.imgur.com/SfatCy2.jpg)
